# Generated by Django 3.1.6 on 2021-02-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25)),
                ('lname', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=35)),
                ('rnum', models.CharField(max_length=28)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('male', 'male'), ('others', 'others')], max_length=15)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
    ]
